import React from 'react';
import { storiesOf } from '@storybook/react';
import { select, withKnobs } from '@storybook/addon-knobs';
import { withInfo } from '@storybook/addon-info';
import { Flag } from '../../src/Components';

const stories = storiesOf('Flag', module);
stories.addDecorator(withKnobs);

stories.add(
  'Standard',
  withInfo('A flag is is used to represent a political state.')(() => {
    const nameLabel = 'Name';
    const nameOptions = [
      'afghanistan',
      'aland islands',
      'albania',
      'algeria',
      'america',
      'american samoa',
      'andorra',
      'angola',
      'anguilla',
      'antigua',
      'argentina',
      'armenia',
      'aruba',
      'australia',
      'austria',
      'azerbaijan',
      'bahamas',
      'bahrain',
      'bangladesh',
      'barbados',
      'belarus',
      'belgium',
      'belize',
      'benin',
      'bermuda',
      'bhutan',
      'bolivia',
      'bosnia',
      'botswana',
      'bouvet island',
      'brazil',
      'british virgin islands',
      'brunei',
      'bulgaria',
      'burkina faso',
      'burma',
      'burundi',
      'caicos islands',
      'cambodia',
      'cameroon',
      'canada',
      'cape verde',
      'cayman islands',
      'central african republic',
      'chad',
      'chile',
      'china',
      'christmas island',
      'cocos islands',
      'colombia',
      'comoros',
      'congo brazzaville',
      'congo',
      'cook islands',
      'costa rica',
      'cote divoire',
      'croatia',
      'cuba',
      'cyprus',
      'czech republic',
      'denmark',
      'djibouti',
      'dominica',
      'dominican republic',
      'ecuador',
      'egypt',
      'el salvador',
      'equatorial guinea',
      'eritrea',
      'estonia',
      'ethiopia',
      'european union',
      'falkland islands',
      'faroe islands',
      'fiji',
      'finland',
      'france',
      'french guiana',
      'french polynesia',
      'french territories',
      'gabon',
      'gambia',
      'georgia',
      'germany',
      'ghana',
      'gibraltar',
      'greece',
      'greenland',
      'grenada',
      'guadeloupe',
      'guam',
      'guatemala',
      'guinea-bissau',
      'guinea',
      'guyana',
      'haiti',
      'heard island',
      'honduras',
      'hong kong',
      'hungary',
      'iceland',
      'india',
      'indian ocean territory',
      'indonesia',
      'iran',
      'iraq',
      'ireland',
      'israel',
      'italy',
      'jamaica',
      'jan mayen',
      'japan',
      'jordan',
      'kazakhstan',
      'kenya',
      'kiribati',
      'kuwait',
      'kyrgyzstan',
      'laos',
      'latvia',
      'lebanon',
      'lesotho',
      'liberia',
      'libya',
      'liechtenstein',
      'lithuania',
      'luxembourg',
      'macau',
      'macedonia',
      'madagascar',
      'malawi',
      'malaysia',
      'maldives',
      'mali',
      'malta',
      'marshall islands',
      'martinique',
      'mauritania',
      'mauritius',
      'mayotte',
      'mexico',
      'micronesia',
      'moldova',
      'monaco',
      'mongolia',
      'montenegro',
      'montserrat',
      'morocco',
      'mozambique',
      'myanmar',
      'namibia',
      'nauru',
      'nepal',
      'netherlands antilles',
      'netherlands',
      'new caledonia',
      'new guinea',
      'new zealand',
      'nicaragua',
      'niger',
      'nigeria',
      'niue',
      'norfolk island',
      'north korea',
      'northern mariana islands',
      'norway',
      'oman',
      'pakistan',
      'palau',
      'palestine',
      'panama',
      'paraguay',
      'philippines',
      'pitcairn islands',
      'poland',
      'portugal',
      'puerto rico',
      'qatar',
      'reunion',
      'romania',
      'russia',
      'rwanda',
      'saint helena',
      'saint kitts and nevis',
      'saint lucia',
      'saint pierre',
      'saint vincent',
      'samoa',
      'san marino',
      'sandwich islands',
      'sao tome',
      'saudi arabia',
      'scotland',
      'senegal',
      'serbia',
      'seychelles',
      'sierra leone',
      'singapore',
      'slovakia',
      'slovenia',
      'solomon islands',
      'somalia',
      'south africa',
      'south korea',
      'spain',
      'sri lanka',
      'sudan',
      'suriname',
      'svalbard',
      'swaziland',
      'sweden',
      'switzerland',
      'syria',
      'taiwan',
      'tajikistan',
      'tanzania',
      'thailand',
      'timorleste',
      'togo',
      'tokelau',
      'tonga',
      'trinidad',
      'tunisia',
      'turkey',
      'turkmenistan',
      'tuvalu',
      'uganda',
      'ukraine',
      'united arab emirates',
      'united kingdom',
      'united states',
      'uruguay',
      'us minor islands',
      'us virgin islands',
      'uzbekistan',
      'vanuatu',
      'vatican city',
      'venezuela',
      'vietnam',
      'wales',
      'wallis and futuna',
      'western sahara',
      'yemen',
      'zambia',
      'zimbabwe'
    ];
    const defaultName = 'united states';
    const nameChange = select(nameLabel, nameOptions, defaultName);
    return <Flag name={nameChange} />;
  })
);
