import React from 'react';
import { storiesOf, action } from '@storybook/react';
import {
  boolean,
  number,
  select,
  text,
  withKnobs
} from '@storybook/addon-knobs';
import { withInfo } from '@storybook/addon-info';
import { Search } from '../../src/Components/Search';

const stories = storiesOf('Search', module);
stories.addDecorator(withKnobs);

stories.add(
  'Standard',
  withInfo(
    'A search module allows a user to query for results from a selection of data.'
  )(() => {
    const alignedOptions = {
      none: '',
      left: 'Left',
      right: 'Right'
    };
    const defaultAlignment = '';
    const alignmentChange = select('Aligned', alignedOptions, defaultAlignment);

    const fluid = boolean('Fluid', false);

    const iconOptions = [
      '500px',
      'add circle',
      'add square',
      'add to calendar',
      'add to cart',
      'add user',
      'add',
      'address book outline',
      'address book',
      'address card outline',
      'address card',
      'adjust',
      'adn',
      'alarm mute outline',
      'alarm mute',
      'alarm outline',
      'alarm',
      'ald',
      'align center',
      'align justify',
      'align left',
      'align right',
      'als',
      'amazon',
      'ambulance',
      'american express card',
      'american express',
      'american sign language interpreting',
      'amex',
      'anchor',
      'android',
      'angellist',
      'angle double down',
      'angle double left',
      'angle double right',
      'angle double up',
      'angle down',
      'angle left',
      'angle right',
      'angle up',
      'announcement',
      'apple',
      'archive',
      'area chart',
      'area graph',
      'arrow circle down',
      'arrow circle left',
      'arrow circle outline down',
      'arrow circle outline left',
      'arrow circle outline right',
      'arrow circle outline up',
      'arrow circle right',
      'arrow circle up',
      'arrow down cart',
      'arrow down',
      'arrow left',
      'arrow right',
      'arrow up',
      'asexual',
      'asl interpreting',
      'asl',
      'assistive listening devices',
      'assistive listening systems',
      'asterisk',
      'at',
      'attach',
      'attention',
      'audio description',
      'backward',
      'balance',
      'ban',
      'bandcamp',
      'bar chart',
      'bar graph',
      'bar',
      'barcode',
      'bars',
      'bath',
      'bathtub',
      'battery empty',
      'battery four',
      'battery full',
      'battery half',
      'battery high',
      'battery low',
      'battery medium',
      'battery one',
      'battery quarter',
      'battery three quarters',
      'battery three',
      'battery two',
      'battery zero',
      'bed',
      'beer',
      'behance square',
      'behance',
      'bell outline',
      'bell slash outline',
      'bell slash',
      'bell',
      'bicycle',
      'binoculars',
      'birthday',
      'bitbucket square',
      'bitbucket',
      'bitcoin',
      'black tie',
      'blind',
      'block layout',
      'bluetooth alternative',
      'bluetooth',
      'bold',
      'bomb',
      'book',
      'bookmark outline',
      'bookmark',
      'braille',
      'briefcase',
      'broken chain',
      'browser',
      'btc',
      'bug',
      'building outline',
      'building',
      'bullhorn',
      'bullseye',
      'bus',
      'buysellads',
      'calculator',
      'calendar check',
      'calendar minus',
      'calendar outline',
      'calendar plus',
      'calendar times',
      'calendar',
      'call square',
      'call',
      'camera retro',
      'camera',
      'cancel',
      'car',
      'caret down',
      'caret left',
      'caret right',
      'caret up',
      'cart',
      'cc',
      'certificate',
      'chain',
      'chat',
      'check circle outline',
      'check circle',
      'check square',
      'check',
      'checked calendar',
      'checkmark box',
      'checkmark',
      'chevron circle down',
      'chevron circle left',
      'chevron circle right',
      'chevron circle up',
      'chevron down',
      'chevron left',
      'chevron right',
      'chevron up',
      'child',
      'chrome',
      'circle notched',
      'circle outline',
      'circle outline',
      'circle thin',
      'circle',
      'clipboard',
      'clock',
      'clone',
      'close',
      'closed captioning',
      'cloud download',
      'cloud upload',
      'cloud',
      'cny',
      'cocktail',
      'code',
      'codepen',
      'codiepie',
      'coffee',
      'cogs',
      'columns',
      'comment outline',
      'comment',
      'commenting outline',
      'commenting',
      'comments outline',
      'comments',
      'comments',
      'compass',
      'compose',
      'compress',
      'computer',
      'configure',
      'connectdevelop',
      'contao',
      'content',
      'conversation',
      'copy',
      'copyright',
      'creative commons',
      'credit card alternative',
      'credit card',
      'crop',
      'crosshairs',
      'css3',
      'cube',
      'cubes',
      'currency',
      'cut',
      'dashboard',
      'dashcube',
      'database',
      'deaf',
      'deafness',
      'delete calendar',
      'delete',
      'delicious',
      'desktop',
      'detective',
      'deviantart',
      'diamond',
      'digg',
      'diners club card',
      'diners club',
      'discover card',
      'discover',
      'discussions',
      'disk outline',
      'dislike outline',
      'doctor',
      'dollar',
      'dont',
      'dot circle outline',
      'download',
      'dribble',
      'drivers license outline',
      'drivers license',
      'dropbox',
      'dropdown',
      'drupal',
      'edge',
      'edit',
      'eercast',
      'eject',
      'ellipsis horizontal',
      'ellipsis vertical',
      'emergency',
      'empire',
      'empty heart',
      'empty star',
      'envelope',
      'envira gallery',
      'envira',
      'erase',
      'eraser',
      'etsy',
      'eur',
      'euro',
      'exchange',
      'exclamation circle',
      'exclamation triangle',
      'exclamation',
      'expand',
      'expeditedssl',
      'external share',
      'external square',
      'external',
      'external',
      'eye',
      'eyedropper',
      'fa',
      'facebook f',
      'facebook official',
      'facebook square',
      'facebook',
      'factory',
      'fast backward',
      'fast forward',
      'favorite',
      'fax',
      'feed',
      'female homosexual',
      'female',
      'fighter jet',
      'file archive outline',
      'file audio outline',
      'file code outline',
      'file excel outline',
      'file image outline',
      'file outline',
      'file pdf outline',
      'file powerpoint outline',
      'file text outline',
      'file text',
      'file video outline',
      'file word outline',
      'file',
      'film',
      'filter',
      'find',
      'fire extinguisher',
      'fire',
      'firefox',
      'first aid',
      'first order',
      'five hundred pixels',
      'flag checkered',
      'flag outline',
      'flag',
      'flask',
      'flickr',
      'folder open outline',
      'folder open',
      'folder outline',
      'folder',
      'font awesome',
      'font',
      'fonticons',
      'food',
      'fork',
      'fort awesome',
      'forumbee',
      'forward',
      'foursquare',
      'free code camp',
      'frown',
      'game',
      'gamepad',
      'gay',
      'gbp',
      'genderless',
      'gg circle',
      'gg',
      'gift',
      'git square',
      'git',
      'github alternate',
      'github square',
      'github',
      'gitlab',
      'gittip',
      'glide g',
      'glide',
      'globe',
      'google plus circle',
      'google plus official',
      'google plus square',
      'google plus',
      'google wallet',
      'google',
      'grab',
      'graduation',
      'gratipay',
      'grav',
      'grid layout',
      'group',
      'h',
      'hacker news',
      'hand lizard',
      'hand outline down',
      'hand outline left',
      'hand outline right',
      'hand outline up',
      'hand paper',
      'hand peace',
      'hand pointer',
      'hand rock',
      'hand scissors',
      'hand spock',
      'hand victory',
      'handicap',
      'hard of hearing',
      'hashtag',
      'hdd outline',
      'header',
      'headphone',
      'heart outline',
      'heart',
      'heartbeat',
      'help circle outline',
      'help circle',
      'help',
      'heterosexual',
      'hide',
      'history',
      'home',
      'hospital',
      'hotel',
      'hourglass empty',
      'hourglass end',
      'hourglass four',
      'hourglass full',
      'hourglass half',
      'hourglass one',
      'hourglass outline',
      'hourglass start',
      'hourglass three',
      'hourglass two',
      'hourglass zero',
      'houzz',
      'html5',
      'i cursor',
      'id badge',
      'id card outline',
      'id card',
      'idea',
      'ils',
      'image',
      'imdb',
      'in cart',
      'inbox',
      'indent',
      'industry',
      'info circle',
      'info',
      'inr',
      'instagram',
      'intergender',
      'internet explorer',
      'intersex',
      'ioxhost',
      'italic',
      'japan credit bureau card',
      'japan credit bureau',
      'jcb',
      'joomla',
      'jpy',
      'jsfiddle',
      'key',
      'keyboard',
      'krw',
      'lab',
      'laptop',
      'lastfm square',
      'lastfm',
      'law',
      'leaf',
      'leanpub',
      'legal',
      'lemon',
      'lesbian',
      'level down',
      'level up',
      'life ring',
      'lightbulb',
      'lightning',
      'like outline',
      'like',
      'line chart',
      'line graph',
      'linkedin square',
      'linkedin',
      'linkify',
      'linkify',
      'linode',
      'linux',
      'lira',
      'list layout',
      'list ol',
      'list ul',
      'list',
      'location arrow',
      'lock',
      'log out',
      'long arrow down',
      'long arrow left',
      'long arrow right',
      'long arrow up',
      'low vision',
      'magic',
      'magnet',
      'magnify',
      'mail forward',
      'mail outline',
      'mail square',
      'mail',
      'male homosexual',
      'male',
      'man',
      'map outline',
      'map pin',
      'map signs',
      'map',
      'marker',
      'mars alternate',
      'mars double',
      'mars horizontal',
      'mars stroke horizontal',
      'mars stroke vertical',
      'mars stroke',
      'mars vertical',
      'mars',
      'mastercard card',
      'mastercard',
      'maxcdn',
      'maximize',
      'meanpath',
      'medium',
      'medkit',
      'meetup',
      'meh',
      'mercury',
      'microchip',
      'microphone slash',
      'microphone',
      'microsoft edge',
      'military',
      'minimize',
      'minus circle',
      'minus square outline',
      'minus square',
      'mixcloud',
      'mobile',
      'modx',
      'money',
      'moon',
      'motorcycle',
      'mouse pointer',
      'move',
      'ms edge',
      'music',
      'mute',
      'neuter',
      'new pied piper',
      'newspaper',
      'non binary transgender',
      'numbered list',
      'object group',
      'object ungroup',
      'odnoklassniki square',
      'odnoklassniki',
      'opencart',
      'openid',
      'opera',
      'optinmonster',
      'options',
      'ordered list',
      'other gender horizontal',
      'other gender vertical',
      'other gender',
      'outdent',
      'pagelines',
      'paint brush',
      'paragraph',
      'paste',
      'pause circle outline',
      'pause circle',
      'pause',
      'paw',
      'payment',
      'paypal card',
      'paypal',
      'pencil square',
      'pencil',
      'percent',
      'phone square',
      'phone',
      'photo',
      'picture',
      'pie chart',
      'pie graph',
      'pied piper alternate',
      'pied piper hat',
      'pied piper',
      'pin',
      'pinterest square',
      'pinterest',
      'pinterest',
      'plane',
      'play circle outline',
      'play circle',
      'play',
      'plug',
      'plus cart',
      'plus circle',
      'plus square outline',
      'plus square',
      'plus',
      'minus',
      'pocket',
      'podcast',
      'point',
      'pointing down',
      'pointing left',
      'pointing right',
      'pointing up',
      'pound',
      'power cord',
      'power',
      'print',
      'privacy',
      'product hunt',
      'protect',
      'puzzle',
      'qq',
      'qrcode',
      'question circle outline',
      'question circle',
      'question',
      'quora',
      'quote left',
      'quote right',
      'r circle',
      'radio',
      'rain',
      'random',
      'ravelry',
      'rebel',
      'record',
      'recycle',
      'reddit alien',
      'reddit square',
      'reddit',
      'refresh',
      'registered',
      'remove bookmark',
      'remove circle outline',
      'remove circle',
      'remove from calendar',
      'remove user',
      'remove',
      'renren',
      'repeat',
      'reply all',
      'reply',
      'resize horizontal',
      'resize vertical',
      'retweet',
      'rmb',
      'road',
      'rocket',
      'rouble',
      'rss square',
      'rss',
      'rub',
      'ruble',
      'rupee',
      's15',
      'safari',
      'save',
      'scribd',
      'search',
      'selected radio',
      'sellsy',
      'send outline',
      'send',
      'server',
      'setting',
      'settings',
      'share alternate square',
      'share alternate',
      'share square',
      'share',
      'shekel',
      'sheqel',
      'shield',
      'ship',
      'shipping',
      'shirtsinbulk',
      'shop',
      'shopping bag',
      'shopping basket',
      'shopping cart',
      'shuffle',
      'shutdown',
      'sidebar',
      'sign in',
      'sign language',
      'sign out',
      'signal',
      'signing',
      'signup',
      'simplybuilt',
      'sitemap',
      'skyatlas',
      'skype',
      'slack',
      'sliders',
      'slideshare',
      'smile',
      'snapchat ghost',
      'snapchat square',
      'snapchat',
      'snowflake outline',
      'soccer',
      'sort alphabet ascending',
      'sort alphabet descending',
      'sort ascending',
      'sort content ascending',
      'sort content descending',
      'sort descending',
      'sort numeric ascending',
      'sort numeric descending',
      'sort',
      'sound',
      'soundcloud',
      'space shuttle',
      'spinner',
      'spoon',
      'spotify',
      'spy',
      'square outline',
      'square',
      'stack exchange',
      'stack overflow',
      'star half empty',
      'star half full',
      'star half',
      'star',
      'steam square',
      'steam',
      'step backward',
      'step forward',
      'sticky note outline',
      'sticky note',
      'stop circle outline',
      'stop circle',
      'stop',
      'street view',
      'strikethrough',
      'stripe card',
      'stripe',
      'student',
      'stumbleupon circle',
      'stumbleupon',
      'subscript',
      'subway',
      'suitcase',
      'sun',
      'superpowers',
      'superscript',
      'table',
      'tablet',
      'tag',
      'tags',
      'talk outline',
      'talk',
      'target',
      'tasks',
      'taxi',
      'telegram',
      'teletype',
      'television',
      'tencent weibo',
      'terminal',
      'text cursor',
      'text height',
      'text telephone',
      'text width',
      'theme isle',
      'theme',
      'themeisle',
      'thermometer empty',
      'thermometer full',
      'thermometer half',
      'thermometer quarter',
      'thermometer three quarters',
      'thermometer',
      'thumb tack',
      'thumbs down',
      'thumbs outline down',
      'thumbs outline up',
      'thumbs up',
      'ticket',
      'time',
      'times rectangle outline',
      'times rectangle',
      'tint',
      'tm',
      'toggle down',
      'toggle left',
      'toggle off',
      'toggle on',
      'toggle right',
      'toggle up',
      'trademark',
      'train',
      'transgender',
      'translate',
      'trash outline',
      'trash',
      'travel',
      'treatment',
      'tree',
      'trello',
      'triangle down',
      'triangle left',
      'triangle right',
      'triangle up',
      'tripadvisor',
      'trophy',
      'truck',
      'try',
      'tty',
      'tumblr square',
      'tumblr',
      'tv',
      'twitch',
      'twitter square',
      'twitter',
      'umbrella',
      'underline',
      'undo',
      'unhide',
      'universal access',
      'university',
      'unlinkify',
      'unlock alternate',
      'unlock',
      'unmute',
      'unordered list',
      'upload',
      'usb',
      'usd',
      'user cancel',
      'user circle outline',
      'user circle',
      'user close',
      'user delete',
      'user outline',
      'user plus',
      'user times',
      'user x',
      'user',
      'users',
      'vcard outline',
      'vcard',
      'venus double',
      'venus mars',
      'venus',
      'viacoin',
      'viadeo square',
      'viadeo',
      'video camera',
      'video play outline',
      'video play',
      'video',
      'vimeo square',
      'vimeo',
      'vine',
      'visa card',
      'visa',
      'vk',
      'volume control phone',
      'volume down',
      'volume off',
      'volume up',
      'wait',
      'warning circle',
      'warning sign',
      'warning',
      'wechat',
      'weibo',
      'weixin',
      'whatsapp',
      'wheelchair',
      'wifi',
      'wifi',
      'wikipedia',
      'window close outline',
      'window close',
      'window maximize',
      'window minimize',
      'window restore',
      'windows',
      'winner',
      'wizard',
      'woman',
      'won',
      'wordpress beginner',
      'wordpress forms',
      'wordpress',
      'world',
      'wpbeginner',
      'wpexplorer',
      'wpforms',
      'wrench',
      'write square',
      'write',
      'x',
      'xing square',
      'xing',
      'y combinator',
      'yahoo',
      'yc',
      'ycombinator',
      'yelp',
      'yen',
      'yoast',
      'youtube play',
      'youtube square',
      'youtube',
      'zip',
      'zoom in',
      'zoom out',
      'zoom'
    ];
    const defaultIcon = 'search';
    const iconChange = select('Icon', iconOptions, defaultIcon);

    const loading = boolean('Loading', false);
    const minCharacters = number('Min Characters', 1);
    const noResultsDescription = text(
      'No Results Description',
      'Extra Content'
    );
    const noResultsMessage = text('No Results Message', 'No results found.');
    const showNoResults = boolean('Show No Results', true);

    const sizeOptions = {
      none: '',
      mini: 'Mini',
      tiny: 'Tiny',
      small: 'Small',
      large: 'Large',
      big: 'Big',
      huge: 'Huge',
      massive: 'Massive'
    };
    const defaultSize = '';
    const sizeChange = select('Size', sizeOptions, defaultSize);
    return (
      <Search
        aligned={alignmentChange}
        fluid={fluid}
        icon={iconChange}
        loading={loading}
        minCharacters={minCharacters}
        noResultsDescription={noResultsDescription}
        noResultsMessage={noResultsMessage}
        onSearchChange={action('changed')}
        showNoResults={showNoResults}
        size={sizeChange}
      />
    );
  })
);
